name: Test dependencies for security issues with Snyk

on: 
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      run: |
        curl -sSL https://github.com/python-poetry/install.python-poetry.org/raw/main/install-poetry.py > install-poetry.py
        python install-poetry.py
    - name: Show environment
      run: | 
        python --version
        pip --version
        poetry --version
    - uses: snyk/actions/setup@master
    - name: Install Python dependencies with Poetry
      run: poetry install -v
   # - name: Run tests
   #   run: poetry run pytest
    - name: Test dependencies with Snyk
      run: |
        pip install -r Source/requirements.txt
        snyk test --all-projects
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    - name: Monitor dependencies for security issues with Snyk
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
