name: "Snyk Code Scan"

on:
  push:
    branches:
      - main
      - Develop
      - Automated_Pipeline

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk@latest
          snyk auth ${SNYK_TOKEN}
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --json --debug > snyk-sarif-report.json
        continue-on-error: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: snyk-sarif-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} 

        
